[tool.poetry]
name = "poethepoet"
version = "0.0.3"
description = "A task runner that works well with poetry."
authors = ["Nat Noordanus <n@natn.me>"]
readme = "README.rst"
license = "MIT"
repository =  "https://github.com/nat-n/poethepoet"
homepage =  "https://github.com/nat-n/poethepoet"

[tool.poetry.dependencies]
python = "^3.6"
toml = "^0.10.1"
poetry = "^1.0.5"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
bpython = "^0.19"
mypy = "^0.770"
pylint = "^2.5.2"
pytest = "^5.2"
pytest-cov = "^2.9.0"

[tool.poetry.scripts]
poe = "poethepoet.cli:main"

[tool.poe]
run_in_project_root = false

[tool.poe.tasks]
# Dev actions
format = "black $POE_ROOT"
clean = """
  # multiline commands including comments work too!
  rm -rf $POE_ROOT/.coverage
         $POE_ROOT/.mypy_cache
         $POE_ROOT/.pytest_cache
         $POE_ROOT/dist
         $POE_ROOT/**/__pycache__
"""
# Code quality checks
test = "pytest --cov=poethepoet ${POE_ROOT}/tests"
types = "mypy $POE_ROOT/poethepoet --ignore-missing-imports"
lint = "pylint $POE_ROOT/poethepoet"
style = "black $POE_ROOT --check --diff"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
