name: CI

on: [push, pull_request]

jobs:

  code-style:
    runs-on: ubuntu-latest

    name: Check coding standards

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - uses: Gr1N/setup-poetry@v2
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install dependencies
        run: poetry install
      - name: Check code formatting
        run: poetry run poe style
      - name: Run linter
        run: poetry run poe lint
      - name: Check types
        run: poetry run poe types

  run-tests:
    runs-on: ubuntu-latest

    name: Run tests

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - uses: Gr1N/setup-poetry@v2
      - name: Install dependencies
        run: poetry install
      - name: Run tests
        run: poetry run poe test

  build-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - uses: Gr1N/setup-poetry@v2
      - name: Build package
        run: poetry build
      - name: Publish package to PyPI
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        run: poetry publish -n
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.pypi }}
